// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS7r4GaqHtYnRkym8uR2wLPFFozEsz_zA',
    appId: '1:559321617691:web:97ce160d0181e27119afbe',
    messagingSenderId: '559321617691',
    projectId: 'mis-lab-4',
    authDomain: 'mis-lab-4.firebaseapp.com',
    storageBucket: 'mis-lab-4.appspot.com',
    measurementId: 'G-M2ZZLP79K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSXd1SdGODdl5o1LlcMTKCWvyI6PiwPxo',
    appId: '1:559321617691:android:84525894c3d583a219afbe',
    messagingSenderId: '559321617691',
    projectId: 'mis-lab-4',
    storageBucket: 'mis-lab-4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw7SnBe0fWc33_xbDZY3UJMqnsbN-lANM',
    appId: '1:559321617691:ios:2f5bf2ce8e0536c419afbe',
    messagingSenderId: '559321617691',
    projectId: 'mis-lab-4',
    storageBucket: 'mis-lab-4.appspot.com',
    iosClientId: '559321617691-vet2meamvi6lvq70ma1i67cdab8pp7h0.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab3Mis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw7SnBe0fWc33_xbDZY3UJMqnsbN-lANM',
    appId: '1:559321617691:ios:2f5bf2ce8e0536c419afbe',
    messagingSenderId: '559321617691',
    projectId: 'mis-lab-4',
    storageBucket: 'mis-lab-4.appspot.com',
    iosClientId: '559321617691-vet2meamvi6lvq70ma1i67cdab8pp7h0.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab3Mis',
  );
}
